CREATE TABLE household_codes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id    BIGINT      NOT NULL,
    code       VARCHAR(10) NOT NULL UNIQUE,
    expiry_date TIMESTAMP   NOT NULL,
    CONSTRAINT fk_household_code_household
        FOREIGN KEY (household_id) REFERENCES HOUSEHOLD(id)
);

INSERT INTO household_codes (household_id, code, expiry_date) VALUES
  (1, '123456', DATEADD('DAY', 7, CURRENT_TIMESTAMP)),
  (2, '123556', DATEADD('DAY', 1, CURRENT_TIMESTAMP));