CREATE TABLE PUBLIC.password_reset_tokens (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
token VARCHAR(255) NOT NULL,
expiry_date TIMESTAMP NOT NULL,
user_id INTEGER NOT NULL,
CONSTRAINT uq_password_reset_tokens_token UNIQUE (token),
CONSTRAINT fk_password_reset_tokens_user FOREIGN KEY (user_id)
REFERENCES PUBLIC.user_account(id)
ON DELETE CASCADE
);

CREATE INDEX idx_password_reset_tokens_user_id
ON PUBLIC.password_reset_tokens(user_id);