CREATE TABLE two_factor_codes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL,
    code       VARCHAR(10) NOT NULL UNIQUE,
    expiry_date TIMESTAMP   NOT NULL,
    CONSTRAINT fk_two_factor_code_user
        FOREIGN KEY (user_id) REFERENCES user_account(id)
);

INSERT INTO two_factor_codes (user_id, code, expiry_date) VALUES
  (1, '123456', DATEADD('DAY', 7, CURRENT_TIMESTAMP)),
  (2, '123556', DATEADD('DAY', 1, CURRENT_TIMESTAMP));