CREATE TABLE TWO_FACTOR_CODE (
    id INT PRIMARY KEY AUTO_INCREMENT,
    user_id INT NOT NULL,
    code VARCHAR(10) NOT NULL UNIQUE,
    expires_at TIMESTAMP NOT NULL
    CONSTRAINT fk_two_factor_code_user FOREIGN KEY (user_id) REFERENCES USER_ACCOUNT(id)
);