package no.ntnu.idatt2106.krisefikser.model;

import java.time.LocalDateTime;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Entity
@NoArgsConstructor
@Getter
@Setter
@Table(name = "event")
/**
 * Entity class representing an event in the system.
 * This class is used to store event information such as name, description, and location attributes. 
 */
public class Event {
  
  /**
   * Unique identifier for the event.
   * This field is automatically generated by the database.
   * It is the primary key of the Event table.
   */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private int id;

  /**
   * Name of the event.
   * This field cannot be null and has a maximum length of 100 characters.
   */
  @Column(nullable = false, length = 100)
  private String name;

  /**
   * Description of the event.
   * This field cannot be null. 
   */
  @Column(nullable = false)
  private String description;

  /**
   * Type of the event. This field is used to determine the icon to be displayed on the map.
   * This field cannot be null and is stored as a string in the database.
   */
  private enum iconType {
    NONE,
    POINT,
    NORMAL,
    DANGER,
    ASSEMBLY_POINT,
    MEDICAL,
    SHELTER,
    OTHER
  }
  @Enumerated(EnumType.STRING)
  private iconType icon;

  /**
   * Start time of the event.
   * This field cannot be null and is stored as a LocalDateTime in the database.
   */
  @Column(nullable = false)
  private LocalDateTime startTime;

  /**
   * End time of the event.
   */
  private LocalDateTime endTime;

  /**
   * Latitude of the event location.
   * This field cannot be null and is stored as a double in the database.
   */
  @Column(nullable = false)
  private Double latitude;

  /**
   * Longitude of the event location.
   * This field cannot be null and is stored as a double in the database.
   */
  @Column(nullable = false)
  private Double longitude;

  /**
   * Radius of the event location in meters.
   * This field cannot be null and is stored as an integer in the database.
   */
  @Column(nullable = false)
  private int radius;

  /**
   * Severity of the event.
   * This field cannot be null and is stored as an integer in the database.
   */
  private int severity;
}
