package no.ntnu.idatt2106.krisefikser.model;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.annotations.media.Schema;

@Schema(description = "User entity representing a user in the system.")
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "user_account")
public class User {
    /**
     * Unique identifier for the user.
     * This field is automatically generated by the database.
     * It is the primary key of the User table.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Schema(description = "Unique identifier for the user.")
    private Long id;

    /**
     * User's email address.
     * This field cannot be null and must be unique.
     */
    @Column(nullable = false)
    @Schema(description = "Email address of the user.")
    private String email;

    /**
     * Username of the User.
     * This field cannot be null and must be unique.
     */
    @Column(nullable = false, unique = true)
    @Schema(description = "Username of the user.")
    private String username;

    /**
     * First name of the User.
     * This field cannot be null and has a maximum length of 50 characters.
     */
    @Schema(description = "First name of the user.", example = "Jonny")
    @Column(nullable = false, length = 50)
    private String firstName;

    /**
     * Last name of the User.
     * This field cannot be null and has a maximum length of 50 characters.
     */
    @Schema(description = "Last name of the user.", example = "Doe")
    @Column(nullable = false, length = 50)
    private String lastName;

    /**
     * Password of the User.
     * This field cannot be null and has a maximum length of 255 characters.
     */
    @Column(nullable = false)
    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    @Schema(description = "Password of the user.")
    private String password;

    /**
     * Enum with roles for the User.
     */
    public enum Role {
        SUPERADMIN,
        ADMIN,
        USER
    }

    /**
     * Role of the User.
     * Can choose between SUPERADMIN, ADMIN, and USER.
     * This field cannot be null and has a default value of USER.
     */
    @Enumerated(EnumType.STRING)
    @Schema(description = "Role of the user.", example = "USER")
    @Column(nullable = false)
    private Role role = Role.USER;

    /**
     * Houshold of the User.
     * This field cannot be null.
     * It is a many-to-one relationship with the Household entity.
     * This means that many users can belong to one household.
     */
    @Schema(description = "Household the user is in", example = "1")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "household_id", nullable = false)
    private Household household;

}

